사진작가 마이페이지 (Feat/#14 mypage p UI)
2023-SWU-Snapfit/SNAPFIT-iOS pull request #18
Opened 2023-05-20 06:55 UTC by Hamthoven

## 작업한 내용
- 디자인에서 캐러셀뷰 셀 크기 101에서 100으로 변경과 같이 다른 거 inset 다 16인데 혼자 17이라던가 이런 것들은 눈치껏 맞춰서 작업.
- Components에 TextboxView와 갤러리, 리뷰는 따로 빼서 파일 만듦.

## PR Point

- 위의 작업 내용과 같이 했는데 이상한 부분은 알려주시오~~
- 탭이랑 네비게이션을 아직 적용 안해서 디자인처럼 되어있는 부분들 중 위에 (상태바까지 사진 차 보이게 하는 거)는 아직 그대로 냅둔 상태.
- 문의하기와 수정하기 버튼은 아직 안만든 게 맞다! (차후 프로필 구성하면서 만들 예정)
- 충돌나는 부분 고치고 Request 하겠습니다~

## 📸 스크린샷

<img width="234" alt="image" src="https://github.com/2023-SWU-Snapfit/SNAPFIT-iOS/assets/86394389/e67cddd1-87bf-49ea-8da7-0a4a0d1efd7e">
<img width="242" alt="image" src="https://github.com/2023-SWU-Snapfit/SNAPFIT-iOS/assets/86394389/67129076-ecba-4eb5-b5ec-08746d62e906">

## 관련 이슈
- Resolved: #14 
- Resolved: #15

2023-05-20 07:15 UTC, Hamthoven commented
충돌나는 파일은 로컬에 복붙한 다음에 오류나는 부분 지우고 파일 열리는 거 확인했다!

2023-05-20 09:15 UTC, dev-madilyn requested changes
TextboxView 네이밍 관련해서만 수정되면 좋을 것 같아요~~
나머지 코멘트는 참고해 주세요!!

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Components/TextboxView.swift
> +class TextboxView: UITextView {
UIKit에서는 TextView라는 명칭을 쓰는데, TextboxView라는 네이밍은 약간.. 뭐랄까 TableView를 ListView라고 하는 느낌이 드네요?!? 만약 이 TextView Class를 Snapfit에서 사용하는 공식(?) TextView로 사용하고 싶다면(아주 제너럴한 이름을 원한 거였다면) SnapfitTextView라고 하는 게 어떨까요??!

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Components/TextboxView.swift
> +"""
text 파라미터의 디폴트 값을
"""
"""
으로 쓴 이유가 있을까요? (""가 아니라..)

그리구 여기에 디폴트 값이 필요한 이유가 무엇인가요?? (궁금...)

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Screens/Mypage/MypagePhotographerViewController.swift
> +        // MARK: - Initialization
엄연히 따지자면 Initialization은 클래스의 인스턴스가 생성될 때를 나타내고,
현재 요 주석이 들어가 있는 viewDidLoad는 인스턴스 생성 -> 뷰 로드 후 실행되는 함수이므로 뭔가 이 주석의 의미(?)가 애매한 것 같습니다..!

![image](https://github.com/2023-SWU-Snapfit/SNAPFIT-iOS/assets/43312096/ceb1b0f7-3de9-4bfa-846e-9424bb11b4e6)


이 이미지 참고해 주세여~!

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Screens/Mypage/MypagePhotographerViewController.swift
> +        self.profileImageView.contentMode = .scaleAspectFill
요런 코드들은
```
private func setProfileImageView() {
        self.profileImageView.setImageColor(color: .sfBlack40)
        self.profileImageView.backgroundColor = .sfBlack40
        self.profileImageView.layer.cornerRadius = 50
        self.profileImageView.layer.borderWidth = 1
        self.profileImageView.layer.borderColor = UIColor.clear.cgColor
        self.profileImageView.clipsToBounds = true
        self.profileImageView.contentMode = .scaleAspectFill
}
```

이런 식으로 쓸 수 있을 것 같아요. viewDidLoad는 뷰를 구성하기 위해 아주 기본적이고 중요한 작업들을 수행하는 곳인데 코드가 너무 길어서 나중에 수정할 때 불편할 것 같다는... 저의 생각입니다...(구냥 의견임...)

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Screens/Mypage/MypagePhotographerViewController.swift
> +        self.profileImageView.contentMode = .scaleAspectFill
또한 viewDidLoad 이후 수행해야 하는 작업 (데이터 넣기 등...)이 아니라면, 우선 제가 주석 달아 준 부분은 해당 프로퍼티 선언부에서도 충분히 해결할 수 있는 코드들인 것 같습니다!! 

```
    let collectionView : UICollectionView = {

        let flowLayout = UICollectionViewFlowLayout()
        flowLayout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        flowLayout.itemSize = CGSize(width: 126, height: 172)
        flowLayout.minimumLineSpacing = 8
        flowLayout.scrollDirection = .horizontal
        let collectionView = UICollectionView(frame: .init(x: 0, y: 0, width: 10, height: 10), collectionViewLayout: flowLayout)
        collectionView.backgroundColor = .clear
        collectionView.showsHorizontalScrollIndicator = false
        return collectionView
    }()
```

위에 이렇게 했잖아여??!! 요렇게요1

2023-05-20 09:15 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Screens/Mypage/MypagePhotographerViewController.swift
> +    }
이 레이아웃들도
private func setLayout() ~ 이렇게 함수로 묶는다면 viewDidLoad 가독성이 더 좋아질 것 같습니다!!

2023-05-22 07:33 UTC, Hamthoven commented
텍스트뷰 없을 경우 보이지 않게 변경 (소개글 외 제목 있는경우는 함께 보이지 않도록 설정)

<img width="324" alt="image" src="https://github.com/2023-SWU-Snapfit/SNAPFIT-iOS/assets/86394389/ed120c32-cf71-4400-b8aa-32f074500acf">
<img width="324" alt="image" src="https://github.com/2023-SWU-Snapfit/SNAPFIT-iOS/assets/86394389/3984a310-6b5b-446d-a306-78098a482df1">

2023-05-22 09:00 UTC, Hamthoven commented
@dev-madilyn 코드 수정 완료! 확인 부탁합니다~

2023-05-22 10:59 UTC, dev-madilyn approved these changes
👍

2023-05-22 10:59 UTC, dev-madilyn commented on SNAPFIT/SNAPFIT/Sources/Screens/Mypage/MypagePhotographerViewController.swift
> +    }
오 ~ 굿굿

2023-05-22 10:59 UTC, dev-madilyn approved these changes
👍

2023-05-22 10:59 UTC, merged